### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by lewwang** [jonas-zhu/JSreverse#1]
你好，请问下巨量算数获取签名和解密数据那里是怎么实现的呀？

**Comment by jonas-zhu** [comment]
获取签名可CSDN搜索方法，我这边hook XMLHttpRequest的send方法截取含有签名的链接。解密数据通过hook JSON找到解密处，使用全局变量接收这个解密函数供全局使用（webpack打包，加载器加载的时候会初始化这个解密函数）。使用浏览器运行js代码，通过sekiro实现远程调用。具体操作可以看info文件。

**Comment by jonas-zhu** [comment]
> 你好，请问下巨量算数获取签名和自己的数据是怎么实现的呀？



> 你好，请问下巨量算数获取签名和自己的数据是怎么实现的呀？

获取签名可CSDN搜索方法，我这个hook XMLHttpRequest的发送方法截取包含签名的链接。数据通过hook JSON获取接口处，用户发送接收这个消息供用户使用（webpack打包，加载器加载的时候会）初始化这个自己运行函数）。使用浏览器js代码，通过sekiro实现远程调用。具体操作可以看info文件。

**Comment by jonas-zhu** [comment]
> 你好，请问下巨量算数获取签名和自己的数据是怎么实现的呀？

获取签名可CSDN搜索方法，hook XMLHttpRequest的send方法截取包含签名的链接。数据解密通过hook JSON获取解密处，用全局变量接收解密函数供全局使用（webpack打包，加载器加载的时候会初始化这个解密函数）。使用浏览器运行js代码，通过sekiro实现远程调用。具体操作可以看info文件。
